import { DUPLICATE_MODES, LeagueEngine } from '../game/engine.js';
import { FORMAT, POKEMON_POOL } from '../game/pokemon.js';
import { hydratePokemon, loadPokemonIndex } from '../game/pokemon-api.js';

const STORAGE_KEY = 'pokedraft-league-v2';
const app = document.querySelector('#app');
let engine = new LeagueEngine({ pokemonPool: POKEMON_POOL });
let league = loadLeague();
let message = '';
let error = '';

function loadLeague() {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY)); } catch { return null; }
}
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(league)); }
function setMessage(text) { message = text; error = ''; render(); }
function setError(text) { error = text; message = ''; render(); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[character])); }
function statSummary(pokemon) { return pokemon.stats?.length ? pokemon.stats.map((stat) => `${stat.name.replace('special-attack', 'SpA').replace('special-defense', 'SpD').replace('attack', 'Atk').replace('defense', 'Def').replace('speed', 'Spe').replace('hp', 'HP')} ${stat.value}`).join(' · ') : 'Stats unavailable'; }
function pokemonCard(pokemon, disabled = false) { return `<article class="pokemon-card"><div class="pokemon-heading"><strong>${escapeHtml(pokemon.name)}</strong>${pokemon.pokedexUrl ? `<a href="${pokemon.pokedexUrl}" target="_blank" rel="noreferrer">PokéDB</a>` : ''}</div><span class="types">${pokemon.types.join(' / ')}</span><span class="ability">${escapeHtml(pokemon.ability)}</span><span class="stats">${escapeHtml(statSummary(pokemon))}</span><button class="button button-small" data-pick="${escapeHtml(pokemon.name)}" ${disabled ? 'disabled' : ''}>${disabled ? 'Drafted' : 'Draft'}</button></article>`; }
function notices() { return [message && `<div class="notice">${escapeHtml(message)}</div>`, error && `<div class="notice error">${escapeHtml(error)}</div>`].filter(Boolean).join(''); }
function renderSetup() {
  app.innerHTML = `<section class="hero"><div><p class="eyebrow">Build a league</p><h2>Draft a roster.<br><span>Make it count.</span></h2><p>Two-player snake draft, local-first records, and comeback rerolls for ${FORMAT}.</p></div></section>${notices()}<div class="grid"><section class="panel"><p class="section-kicker">01 / League setup</p><div class="form-grid"><label>Player one<input id="player-one" value="Ash" maxlength="24"></label><label>Player two<input id="player-two" value="Misty" maxlength="24"></label></div><label>Duplicate Pokémon rules</label><div class="mode-options"><label class="mode-option"><input type="radio" name="duplicate-mode" value="league" checked>No duplicates anywhere <span>Every Pokémon can be drafted once.</span></label><label class="mode-option"><input type="radio" name="duplicate-mode" value="players">Between players only <span>No repeats within a roster.</span></label><label class="mode-option"><input type="radio" name="duplicate-mode" value="unlimited">Unlimited <span>Anything goes, including same-team repeats.</span></label></div><div class="actions"><button class="button" id="start-button">Generate 12 Pokémon</button></div></section></div>`;
  document.querySelector('#start-button').addEventListener('click', startLeague);
}
async function startLeague() { const startButton = document.querySelector('#start-button'); startButton.disabled = true; startButton.textContent = 'Loading Pokémon database...'; try { engine.pokemonPool = await loadPokemonIndex(); const mode = document.querySelector('input[name="duplicate-mode"]:checked').value; league = engine.createLeague({ playerNames: [document.querySelector('#player-one').value, document.querySelector('#player-two').value], duplicateMode: mode }); engine.generateDraftPool(league); league.draft.pool = await hydratePokemon(league.draft.pool); save(); render(); } catch (caught) { setError(`Could not load the Pokémon database: ${caught.message}`); } }
function renderDraft() {
  const currentPlayer = league.players[league.draft.currentPick % 2];
  const draftedNames = new Set(league.draft.picks.map((pick) => pick.pokemon.name));
  app.innerHTML = `<section class="hero"><div><p class="eyebrow">${escapeHtml(FORMAT)}</p><h2>Make pick <span>${league.draft.currentPick + 1}</span> of 12.</h2><p><strong>${escapeHtml(currentPlayer.name)}</strong> is on the clock. The snake order alternates each pick.</p></div></section>${notices()}<div class="grid"><section class="panel"><div class="status-line"><span>Draft pool</span><strong>${league.draft.pool.length - draftedNames.size} available</strong></div><div class="pool">${league.draft.pool.map((pokemon) => pokemonCard(pokemon, draftedNames.has(pokemon.name))).join('')}</div></section><section class="panel"><p class="section-kicker">Your boards</p><div class="rosters">${league.players.map(rosterMarkup).join('')}</div></section></div>`;
  document.querySelectorAll('[data-pick]').forEach((button) => button.addEventListener('click', () => makePick(button.dataset.pick)));
}
function rosterMarkup(player) { return `<div class="roster"><div class="roster-header"><div><h3>${escapeHtml(player.name)}</h3><span class="record">${player.roster.length} / 6 picked</span></div></div><ul class="roster-list">${player.roster.map((pokemon) => `<li>${escapeHtml(pokemon.name)}<span>${pokemon.types.join(' / ')}</span></li>`).join('') || '<li class="empty">Waiting for first pick</li>'}</ul></div>`; }
function makePick(name) { try { engine.pick(league, name); save(); render(); } catch (caught) { setError(caught.message); } }
function renderLeague() {
  app.innerHTML = `<section class="hero"><div><p class="eyebrow">League room / ${escapeHtml(FORMAT)}</p><h2>Play the long game.</h2><p>Record a battle below. Loss streaks unlock increasingly generous rerolls.</p></div></section>${notices()}<div class="grid"><section class="panel half"><p class="section-kicker">Standings</p><table class="standings"><thead><tr><th>Player</th><th>W-L</th><th>Streak</th></tr></thead><tbody>${league.players.map((player) => `<tr><td><strong>${escapeHtml(player.name)}</strong></td><td>${player.wins}-${player.losses}</td><td class="loss-streak">${player.lossStreak ? `${player.lossStreak} loss${player.lossStreak === 1 ? '' : 'es'}` : '-'}</td></tr>`).join('')}</tbody></table><div class="actions">${league.players.map((player) => `<button class="button" data-winner="${player.id}">${escapeHtml(player.name)} won</button>`).join('')}</div></section><section class="panel half"><p class="section-kicker">Rerolls</p>${rerollMarkup()} </section><section class="panel"><p class="section-kicker">Rosters</p><div class="rosters">${league.players.map(rosterMarkup).join('')}</div></section><section class="panel"><p class="section-kicker">Match log</p>${league.matches.length ? `<table class="standings"><tbody>${league.matches.slice().reverse().map((match) => `<tr><td>${escapeHtml(league.players.find((player) => player.id === match.winnerId).name)} defeated ${escapeHtml(league.players.find((player) => player.id === match.loserId).name)}</td><td>${new Date(match.playedAt).toLocaleDateString()}</td></tr>`).join('')}</tbody></table>` : '<p class="empty">No matches recorded yet.</p>'}</section></div>`;
  document.querySelectorAll('[data-winner]').forEach((button) => button.addEventListener('click', () => recordMatch(button.dataset.winner)));
  document.querySelectorAll('[data-reroll]').forEach((button) => button.addEventListener('click', () => createReroll(button.dataset.reroll)));
}
function rerollMarkup() { const pending = league.rerolls.find((reroll) => !reroll.resolved); if (pending) { const player = league.players.find((entry) => entry.id === pending.playerId); return `<p>All ${pending.candidates.length} candidate${pending.candidates.length === 1 ? '' : 's'} are shown. Accept any subset and choose a roster slot for each.</p><form id="reroll-form"><div class="reroll-list">${pending.candidates.map((pokemon, index) => `<label class="mode-option"><input type="checkbox" name="candidate" value="${index}"><span><strong>${escapeHtml(pokemon.name)}</strong> · ${pokemon.types.join(' / ')}<br><small>${escapeHtml(pokemon.ability)}</small><br><small>${escapeHtml(statSummary(pokemon))}</small>${pokemon.pokedexUrl ? `<br><a href="${pokemon.pokedexUrl}" target="_blank" rel="noreferrer">View PokéDB</a>` : ''}</span><select name="replacement-${index}"><option value="">Discard candidate</option>${player.roster.map((rosterPokemon) => `<option value="${escapeHtml(rosterPokemon.name)}">Replace ${escapeHtml(rosterPokemon.name)}</option>`).join('')}</select></label>`).join('')}</div><div class="actions"><button class="button" type="submit">Resolve reroll</button></div></form>`; } const available = league.players.filter((player) => player.rerollAvailable); return available.length ? `<p class="empty">A reroll is ready for:</p><div class="actions">${available.map((player) => `<button class="button" data-reroll="${player.id}">${escapeHtml(player.name)} (${player.lossStreak} candidate${player.lossStreak === 1 ? '' : 's'})</button>`).join('')}</div>` : '<p class="empty">Losses will create rerolls here.</p>'; }
function recordMatch(winnerId) { try { engine.recordMatch(league, winnerId); save(); render(); } catch (caught) { setError(caught.message); } }
async function createReroll(playerId) { try { const reroll = engine.createRerollCandidates(league, playerId); reroll.candidates = await hydratePokemon(reroll.candidates); save(); render(); document.querySelector('#reroll-form').addEventListener('submit', resolveReroll); } catch (caught) { setError(caught.message); } }
function resolveReroll(event) { event.preventDefault(); const pending = league.rerolls.find((reroll) => !reroll.accepted.length); const formData = new FormData(event.currentTarget); const replacements = [...new Set(formData.getAll('candidate'))].map((index) => ({ candidateName: pending.candidates[Number(index)].name, rosterName: formData.get(`replacement-${index}`) })).filter((replacement) => replacement.rosterName); try { engine.resolveReroll(league, pending.id, replacements); save(); setMessage('Reroll resolved.'); } catch (caught) { setError(caught.message); } }
function render() { league ? (league.phase === 'draft' ? renderDraft() : renderLeague()) : renderSetup(); }
document.querySelector('#reset-button').addEventListener('click', () => { localStorage.removeItem(STORAGE_KEY); league = null; message = ''; error = ''; render(); });
render();
